#!/usr/bin/env python3
import os
import sys

from tooling.metadata import BuildMetadata
from tooling.command import Command

# Get the current script's directory
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
META_FILE = "build_meta.json"

metadata = BuildMetadata(CURRENT_DIR, f"{CURRENT_DIR}/{META_FILE}")


def main():
    if len(sys.argv) < 2:
        Command.registeredCommands["help"].run(metadata, None)
        sys.exit(1)

    commandName = sys.argv[1]
    commandArguments = sys.argv[2:] if len(sys.argv) > 2 else []
    command = Command.registeredCommands.get(commandName)
    if not command:
        print(f"Unknown command: {commandName}\n")
        Command.registeredCommands["help"].run(metadata, None)
        sys.exit(1)

    try:
        command.execute(metadata, commandArguments)
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
